config/routes.rb
Rails.application.routes.draw do
  get 'questionnaire/:token/new' => 'questionnaire#new', as: :questionnaire
  patch 'questionnaire/create'
  get 'questionnaire/show'
  get 'questionnaire/notfound'

  root 'dashboard#index'
  get 'dashboard/index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destroy', as: :logout
  get 'login/edit' => 'sessions#edit', as: :edit_login
  patch 'login' => 'sessions#update'
  put 'login' => 'sessions#update'

  get 'signup' => 'authors#new'
  post 'signup' => 'authors#create', as: :authors
  delete 'signup' => 'authors#destroy'
  get 'profile' => 'authors#edit', as: :edit_profile
  patch 'profile' => 'authors#update', as: :author

  delete 'surveys/:id' => 'surveys#destroy'
  patch 'surveys/:id' => 'surveys#update'
  get 'surveys/:token/show' => 'surveys#show', as: :show_survey
  resources :surveys, except: [:index, :show, :patch, :delete]
  patch 'publish/:id' => 'surveys#publish', as: :publish
  patch 'unpublish/:id' => 'surveys#unpublish', as: :unpublish

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate

  def index
    @unpublished_surveys = Survey.where('author_id = ? AND token IS ?', session[:user_id], nil)
    @published_surveys = Survey.where('author_id = ? AND token IS NOT ?', session[:user_id], nil)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div id="pubdSurveys">
  <h2 class="divTitle">Published Surveys</h2>
  <div class="pubSurveyList">
    <div class="noPubSurveys">You have no published surveys</div>
    <% @published_surveys.each do |survey| %>
      <div class="survey">
        <div class="surveyName"><%= survey.title %></div>
        <div class="surveyActions">
          <a href="<%= show_survey_path(survey.token)%>"><i class="fa fa-bar-chart"></i></a>
          <div class="unpubButton"><%= link_to 'Unpublish', unpublish_path(survey), method: :patch %></div>
          <div class="deleteButton">Delete survey</div>
          <div class = "deleteModal">
            <%= hidden_field_tag 'survey_id', survey.id %>
            <div class = "modal-content">
              <h1 class = "modal-header">Are you sure?</h1>
              <h1> You can't undo this.</h1>
              <div class="button-wrap">
                <button type="button" class="cancel-button">Cancel</button>
                <div class="deleteButton"><%= link_to 'Delete', survey, method: :delete %></div>
              </div>
            </div>
          </div>
          <%= hidden_field_tag 'survey_id', survey.id %>
        </div>
        <div class="surveyShare" title="Use this URL to share your survey">
          <div class="shareIcon">SHARE: </div>
          <div class="surveyLink"><%= questionnaire_url(survey.token) %></div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div id="savedSurveys">
  <h2 class="divTitle">Surveys in Progress</h2>
  <div class="savedSurveyList">
    <div class="noSavedSurveys">You haven't started any new surveys</div>
    <a href="<%= new_survey_path %>"><div class="newSurvey"><i id="plus" class="fa fa-plus-square"></i>Create a New Survey</div></a>
      <% @unpublished_surveys.each do |survey| %>
        <div class="survey">
          <div class="surveyName"><%= survey.title %></div>
          <div class="surveyActions">
            <div class="editButton"><%= link_to 'Edit', edit_survey_path(survey) %></div>
            <div class="pubButton"><%= link_to 'Publish', publish_path(survey), method: :patch %></div>
            <div class="deleteButton">Delete survey</div>
            <div class = "deleteModal">
              <%= hidden_field_tag 'survey_id', survey.id %>
              <div class = "modal-content">
                <h1 class = "modal-header">Are you sure?</h1>
                <h1> You can't undo this.</h1>
                <div class="button-wrap">
                  <button type="button" class="cancel-button">Cancel</button>
                  <div class="deleteButton"><%= link_to 'Delete', survey, method: :delete %></div>
                </div>
              </div>
            </div>
            <%= hidden_field_tag 'survey_id', survey.id %>
          </div>
        </div>

      <% end %>
  </div>
</div>