config/routes.rb
Rails.application.routes.draw do
  get 'questionnaire/:token/new' => 'questionnaire#new', as: :questionnaire
  patch 'questionnaire/create'
  get 'questionnaire/show'
  get 'questionnaire/notfound'

  root 'dashboard#index'
  get 'dashboard/index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destroy', as: :logout
  get 'login/edit' => 'sessions#edit', as: :edit_login
  patch 'login' => 'sessions#update'
  put 'login' => 'sessions#update'

  get 'signup' => 'authors#new'
  post 'signup' => 'authors#create', as: :authors
  delete 'signup' => 'authors#destroy'
  get 'profile' => 'authors#edit', as: :edit_profile
  patch 'profile' => 'authors#update', as: :author

  delete 'surveys/:id' => 'surveys#destroy'
  patch 'surveys/:id' => 'surveys#update'
  get 'surveys/:token/show' => 'surveys#show', as: :show_survey
  resources :surveys, except: [:index, :show, :patch, :delete]
  patch 'publish/:id' => 'surveys#publish', as: :publish
  patch 'unpublish/:id' => 'surveys#unpublish', as: :unpublish

end

app/controllers/questionnaire_controller.rb
class QuestionnaireController < ApplicationController
  def new
    @survey = Survey.where(token: params[:token]).first
    unless @survey
      redirect_to questionnaire_notfound_path
    end
    @taker = Taker.create
    @taker.token_create
  end

  def create
    @survey = Survey.find(survey_params[:id])
    # byebug
    if @survey.update(survey_params)
      redirect_to questionnaire_show_path, notice: 'Survey was successfully taken.'
    else
      @taker = Taker.find(survey_params[:questions_attributes]["0"][:answers_attributes]["0"][:taker_id])
      render :new
    end
  end

  def show
  end

  def notfound
  end

  private def survey_params
    params.require(:survey).permit(:id, questions_attributes: [:id, answers_attributes: [:id, :answer, :taker_id, :_destroy]])
  end

end

app/helpers/questionnaire_helper.rb
module QuestionnaireHelper
end

app/views/questionnaire/new.html.erb
<div class = "new-survey-content">
  <%= form_for(@survey, url: questionnaire_create_path) do |f| %>
    <% if @survey.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

        <ul>
        <% @survey.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div>
        <%= f.hidden_field :id %>
        <%= f.fields_for :questions do |ff| %>
          <div>
            <%= ff.hidden_field :id %>
            <% ff.text_field :question_text %>
            <%= ff.object.question_text %>
            <%= ff.fields_for :answers, ff.object.answers.build do |fff| %>
              <div>
                <%= fff.hidden_field :taker_id, value: @taker.id %>
                <% case ff.object.question_type.category %>
                  <% when "Short" %>
                    <%= fff.text_field :answer, placeholder: "Answer" %>
                  <% when "Long" %>
                    <%= fff.text_area :answer, placeholder: "Answer" %>
                  <% when "Radio" %>
                    <% ff.object.options.each do |o| %>
                      <% if o.option %>
                        <%= fff.label :answer_option, o.option %>
                        <%= fff.radio_button :answer, o.value %>
                      <% else %>
                        <%= fff.label :answer_option, o.value %>
                        <%= fff.radio_button :answer, o.value %>
                      <% end %>
                    <% end %>
                  <% when "DropDown" %>
                    <% drop_down_options = [] %>
                    <% ff.object.options.each do |o| %>
                      <% if o.option %>
                        <% drop_down_options << [o.option, o.value] %>
                      <% else %>
                        <% drop_down_options << [o.value, o.value] %>
                      <% end %>
                    <% end %>
                    <%= fff.select :answer, options_for_select(drop_down_options), prompt: "Select an Answer" %>
                <% end %>
                <% if ff.object.required %>
                  <span class="required_question">*<span>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
    </div>
    <div>
      <%= f.submit %>
    </div>
  <% end %>
  <p class = "req-question">*indicates required question</p>
</div>

app/views/questionnaire/notfound.html.erb
<%= image_tag asset_url("file_not_found.jpg"), class: "questionnaire-image" %>

<div class="not-found">
  <h1> Questionnaire not found</h1>
</div>

<div class="not-found-link"><%= link_to "Sign Up", signup_path %><br>
<%= link_to 'Login', login_path %></div>

app/views/questionnaire/show.html.erb
<%= image_tag asset_url("thank_you.jpg"), class: "questionnaire-image" %>

<div class="thank-you">
  <h1> Thank you for taking the Survey </h1>
</div>

<div class="thank-link"><%= link_to 'Sign Up', signup_path %><br>
  <%= link_to 'Login', login_path %>
</div>