config/routes.rb
Rails.application.routes.draw do
  get 'questionnaire/:token/new' => 'questionnaire#new', as: :questionnaire
  patch 'questionnaire/create'
  get 'questionnaire/show'
  get 'questionnaire/notfound'

  root 'dashboard#index'
  get 'dashboard/index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'login' => 'sessions#destroy', as: :logout
  get 'login/edit' => 'sessions#edit', as: :edit_login
  patch 'login' => 'sessions#update'
  put 'login' => 'sessions#update'

  get 'signup' => 'authors#new'
  post 'signup' => 'authors#create', as: :authors
  delete 'signup' => 'authors#destroy'
  get 'profile' => 'authors#edit', as: :edit_profile
  patch 'profile' => 'authors#update', as: :author

  delete 'surveys/:id' => 'surveys#destroy'
  patch 'surveys/:id' => 'surveys#update'
  get 'surveys/:token/show' => 'surveys#show', as: :show_survey
  resources :surveys, except: [:index, :show, :patch, :delete]
  patch 'publish/:id' => 'surveys#publish', as: :publish
  patch 'unpublish/:id' => 'surveys#unpublish', as: :unpublish

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <span>
  <title>SurveyOpossum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
</head>
  <body>

    <header class="header">
      <div class="appInfo">
        <a href="<%= root_path %>"><%= image_tag asset_url("possum-vector-white.png"), class: "opposumicon" %></a>
        <div class = "app-name">Survey Opossum</div>
      </div>
      <div class="userInfo">
        <span class="userName">
          <%= p "Hi, #{Author.find(session[:user_id]).first_name}" unless session[:user_id] == nil %>
        </span>
        <i id="downCaret" class="fa fa-chevron-circle-down fa-2x"></i>
        <div class="profile_dropdown">
          <div class="dropdownItem"> <%= link_to "Edit Profile", edit_profile_path %></div>
          <div class="dropdownItem"><%=  link_to "Change Password", edit_login_path %></div>
          <div class="dropdownItem"><%= link_to "Sign Out", logout_path, method: :delete %></div>
        </div>
      </div>
    </header>
  <%= yield %>

  </body>
</html>